const translations = {
  en: {
    appTitle: "CLUB Scheduler™",
    home: "Home",
    players: "Players",
    rounds: "Rounds",
    summary: "Summary",
    fontSize: "Font Size",
    reset: "Reset",
    resetAll: "Reset",
    resetExcept: "Reset Games",
    enterCourts: "Enter Number of Courts",
    importPlayers: "Import Multiple Players",
    gender: "Gender",
    male: "Male",
    female: "Female",
    import: "Import",
    cancel: "Cancel",
    enterPlayerName: "Enter Player Name",
    addPlayer: "Add Player",
    fixedPairs: "Set Fixed Pairs (Optional)",
    add: "Add",
    pround: "« Round",
    nround: "Round »",
    roundShort: "R",
    rank: "Rank",
    name: "Name",
    played: "Played",
    rested: "Rested",
    importExample: "Name,Gender\nKari,Male\nBhavani,Female",
    Timer: "Timer",
    min: "min",
    selectPlayer1: "Select Player 1",
    selectPlayer2: "Select Player 2",
    small: "Small",
    medium: "Medium",
    large: "Large",
    maxcourts: "Enter Number of Courts",
    sittingOut: "Sitting Out:",
    courts: "Courts"
   
  },
  jp: {
    appTitle: "CLUB Scheduler™",
    home: "ホーム",
    players: "選手一覧",
    rounds: "試合ラウンド",
    summary: "集計",
    fontSize: "文字サイズ",
    reset: "リセット",
    resetAll: "全てをリセット",
    resetExcept: "プレーヤー以外をリセット",
    enterCourts: "コート数を入力",
    importPlayers: "複数選手を取り込み",
    gender: "性別",
    male: "男",
    female: "女",
    import: "取り込み",
    cancel: "キャンセル",
    enterPlayerName: "選手名を入力",
    addPlayer: "選手追加",
    fixedPairs: "固定ペア設定（任意）",
    add: "追加",
    pround: "« ラウンド",
    nround: "ラウンド »",
    roundShort: "R",
    rank: "順位",
    name: "名前",
    played: "試合数",
    rested: "休憩数",
    importExample: "名前,性別\nカリ,男\nババニ,女",
    Timer: "タイマー",
    min: "分",
    selectPlayer1: "プレーヤー1を選択",
    selectPlayer2: "プレーヤー2を選択",
    small: "小",
    medium: "中",
    large: "大",
    maxcourts: "コートの数を入力してください",
    sittingOut: "休憩中:",
    courts: "コート"
    

  }
};






